export const ACCOUNT_SIGNUP_REQUESTED = 'ACCOUNT_SIGNUP_REQUESTED';
export const ACCOUNT_SIGNUP_SUCCESSED = 'ACCOUNT_SIGNUP_SUCCESSED';
export const ACCOUNT_SIGNUP_FAILED = 'ACCOUNT_SIGNUP_FAILED';

export const ACCOUNT_SIGNIN_REQUESTED = 'ACCOUNT_SIGNIN_REQUESTED';
export const ACCOUNT_SIGNIN_SUCCESSED = 'ACCOUNT_SIGNIN_SUCCESSED';
export const ACCOUNT_SIGNIN_FAILED = 'ACCOUNT_SIGNIN_FAILED';

export const ACCOUNT_SIGNOUT_REQUESTED = 'ACCOUNT_SIGNOUT_REQUESTED';
export const ACCOUNT_SIGNOUT_SUCCESSED = 'ACCOUNT_SIGNOUT_SUCCESSED';
export const ACCOUNT_SIGNOUT_FAILED = 'ACCOUNT_SIGNOUT_FAILED';

export const ACCOUNT_FETCH_REQUESTED = 'ACCOUNT_FETCH_REQUESTED';
export const ACCOUNT_FETCH_SUCCESSED = 'ACCOUNT_FETCH_SUCCESSED';
export const ACCOUNT_FETCH_FAILED = 'ACCOUNT_FETCH_FAILED';
